# Generated by Django 3.0.9 on 2020-08-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.FileField(upload_to='static/documents/%Y/%m/%d'),
        ),
    ]
